version: "3.8"

services:
  geth: # this is Optimism's geth client
    build: ../
    ports:
      - 8545:8545 # RPC
      - 8547:8546 # websocket
      - 30303:30303 # P2P TCP (currently unused)
      - 30303:30303/udp # P2P UDP (currently unused)
      - 7301:6060 # metrics
    command: ["sh", "/scripts/geth-entrypoint.sh", "mainnet"]
    volumes:
      - ../scripts:/scripts
      - /home/ubuntu/datadir_mainnet:/home/ubuntu/datadir_mainnet
    container_name: op-geth-mainnet

  node:
    build: ../
    depends_on:
      - geth
    ports:
      - 7545:8545 # RPC
      - 9222:9222 # P2P TCP
      - 9222:9222/udp # P2P UDP
      - 7300:7300 # metrics
      - 6060:6060 # pprof
    command: ["sh", "/scripts/op-node-entrypoint.sh", "mainnet"]
    volumes:
      - ../scripts:/scripts
    container_name: op-node-mainnet
